name: Create Fritzing part package
description: Create a .fzpz archive from part folder and version extracted from the part file
inputs:
  part_folder_path:
    description: 'Path to the part folder'
    required: true
  path_file_path:
    description: 'Path to the .fzp file used to extract version'
    required: true
outputs:
  fzpz_path:
    description: 'Generated .fzpz artifact path'
    value: ${{ steps.create.outputs.fzpz_path }}
runs:
  using: "composite"
  steps:
    - name: Create part package archive
      id: create
      shell: bash
      run: |
        set -e
        set -x
        echo "--- PART_FOLDER_PATH=${{ inputs.part_folder_path }}"
        echo "--- PATH_FILE_PATH=${{ inputs.path_file_path }}"
        VERSION=$(grep -oP '(?<=<version>)[^<]+' "${{ inputs.path_file_path }}" | head -n 1)
        echo "--- Extracted version: $VERSION"
        [ -n "$VERSION" ] || { echo "--- ERROR: Version not found!" >&2; exit 1; }
        OUT_FILE="${{ inputs.part_folder_path }}-v$VERSION.fzpz"
        echo "--- Output archive: $OUT_FILE"
        rm -f "$OUT_FILE"
        echo "--- Creating archive from folder ${ { inputs.part_folder_path }}"
        pushd "${{ inputs.part_folder_path }}"
        zip -0 -r "../$OUT_FILE" .
        popd
        ls -l "$OUT_FILE"
        echo "fzpz_path=$OUT_FILE" >> $GITHUB_OUTPUT