name: Build and Release Fritzing part package

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Ensure zip is installed
        run: |
          sudo apt-get update -y
          sudo apt-get install -y zip

      - name: Determine part version
        id: determine-version
        uses: ./.github/actions/fritzing-determine-version
        with:
          part_path: 'ZS-042 Real Time Clock Module - 4 pin only/part.zs-042-4-pin-only.fzp'

      - name: Create fzpz archive
        id: create-part-package
        uses: ./.github/actions/fritzing-create-part-package
        with:
          part_dir: 'ZS-042 Real Time Clock Module - 4 pin only'
          version: '${{ steps.determine-version.outputs.version }}'

      - name: Upload build artifact
        uses: actions/upload-artifact@v7
        with:
          name: '${{ steps.create-part-package.outputs.fzpz_path }}'
          path: '${{ steps.create-part-package.outputs.fzpz_path }}'
          archive: false

  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Ensure zip is installed
        run: |
          sudo apt-get update -y
          sudo apt-get install -y zip

      - name: Determine part version
        id: determine-version
        uses: ./.github/actions/fritzing-determine-version
        with:
          part_path: 'ZS-042 Real Time Clock Module - 4 pin only/part.zs-042-4-pin-only.fzp'

      - name: Create fzpz archive for release
        id: create-part-package
        uses: ./.github/actions/fritzing-create-part-package
        with:
          part_dir: 'ZS-042 Real Time Clock Module - 4 pin only'
          version: '${{ steps.determine-version.outputs.version }}'

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: '${{ steps.create-part-package.outputs.fzpz_path }}'
          asset_name: '${{ steps.create-part-package.outputs.fzpz_path }}'
          asset_content_type: application/zip
