name: Release Fritzing part package

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Ensure zip is installed
        run: |
          sudo apt-get update -y
          sudo apt-get install -y zip

      - name: Create fzpz archive for ZS-042
        id: create-part-package-zs-042
        uses: ./.github/actions/fritzing-create-part-package
        with:
          part_folder_path: 'ZS-042 Real Time Clock Module - 4 pin only'
          path_file_path: 'ZS-042 Real Time Clock Module - 4 pin only/part.zs-042-4-pin-only.fzp'

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: '${{ steps.create-part-package-zs-042.outputs.fzpz_path }}'
          asset_name: '${{ steps.create-part-package-zs-042.outputs.fzpz_path }}'
          asset_content_type: application/zip

      - name: Create fzpz archive for ESP32-WROOM-32
        id: create-part-package-esp32
        uses: ./.github/actions/fritzing-create-part-package
        with:
          part_folder_path: 'ESP32-WROOM-32-simple-pcb'
          path_file_path: 'ESP32-WROOM-32-simple-pcb/part.ESP32-WROOM-32-simple-pcb.fzp'

      - name: Upload release asset for ESP32-WROOM-32
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: '${{ steps.create-part-package-esp32.outputs.fzpz_path }}'
          asset_name: '${{ steps.create-part-package-esp32.outputs.fzpz_path }}'
          asset_content_type: application/zip          
